"""Add github link to projects model

Revision ID: 1a03663aad29
Revises: 8d9e19515f7c
Create Date: 2026-01-11 19:05:57.228820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a03663aad29'
down_revision: Union[str, Sequence[str], None] = '8d9e19515f7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('github_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'github_link')
    # ### end Alembic commands ###
