"""add image uuid to content_blocks

Revision ID: 5370bc126d3a
Revises: 847f8732f382
Create Date: 2026-01-20 17:17:13.318627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5370bc126d3a'
down_revision: Union[str, Sequence[str], None] = '847f8732f382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_blocks', sa.Column('image_uuid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_blocks', 'image_uuid')
    # ### end Alembic commands ###
