"""content block model

Revision ID: 847f8732f382
Revises: 1a03663aad29
Create Date: 2026-01-19 18:41:33.835898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '847f8732f382'
down_revision: Union[str, Sequence[str], None] = '1a03663aad29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_type', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text_content', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('image_alt_text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_unique_constraint(None, 'users', ['is_admin'])

    # Partial Unique Constraint
    # Allow many false, only one true
    op.create_index(
        'uq_single_admin',
        'users',
        ['is_admin'],
        unique=True,
        postgresql_where=sa.text('is_admin = TRUE')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_table('content_blocks')
    # ### end Alembic commands ###
